name: Repository initialization
on:
  push:
    branches:
      - main
permissions: write-all

jobs:
  repo-determinating:
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2
        
      - name: Checking template repository
        id: checking-template-repository
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          REPO_NAME=${REPO_NAME#*/}
          if [[ "${REPO_NAME}" == *"template"* ]]; then
            echo "Repository is template"
            echo "REPO_IS_TEMPLATE=true" >> $GITHUB_OUTPUT
          else
            echo "Repository is NOT template"
            echo "REPO_IS_TEMPLATE=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Checking initialization
        id: checking-initialization
        run: |
          RUN_NUMBER=${{ github.run_number }}
          echo "RUN_NUMBER = ${RUN_NUMBER}"
          if [ "${RUN_NUMBER}" != 1 ]; then
            echo "Not initial commit (remove this step to action trigger on all commits)"
            echo "COMMIT_IS_INIT=false" >> $GITHUB_OUTPUT
          else
            echo "This commit is initial"
            echo "COMMIT_IS_INIT=true" >> $GITHUB_OUTPUT
          fi
        
    outputs:
      repo-is-template: ${{ steps.checking-template-repository.outputs.REPO_IS_TEMPLATE }}
      commit-is-init: ${{ steps.checking-initialization.outputs.COMMIT_IS_INIT }}



  # README.md initialization job
  init-readme:
    needs: repo-determinating
    if: ${{ needs.repo-determinating.outputs.repo-is-template == 'false' && needs.repo-determinating.outputs.commit-is-init == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Add collaborator
        run: |
          curl -X PUT \
            -H "Authorization: token ${{ secrets.REPO_SETTINGS_ADMIN_CLASSIC_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/collaborators/ShurupJosephson"

      - name: Init README.md with Collaborators
        run: |
          touch collaborators.txt
          LOGINS_FILE_PATH=".github/workflows/config-gh-tg-logins.json"
          
          collaborators=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/collaborators" | jq -r '.[].login')
          for collaborator in ${collaborators[@]}; do
            echo -e "**GitHub:** $collaborator  |  **Telegram:** $(jq -r '.$collaborator' $LOGINS_FILE_PATH)" >> collaborators.txt
          done
          
          collaborators_num=$(wc -l < "collaborators.txt")

          cp ".github/workflows/INIT_README.md" "README.md"
          
          collabs_start_ind=$(grep -F -n "<a id=repo_collaborators></a>" README.md | cut -d ":" -f 1)

          echo -e "\n" >> collaborators.txt
          if [ "$collaborators_num" -eq 0 ]; then
              echo "Коллабораторов нет" > collaborators.txt
          fi
          sed -i "$(expr $collabs_start_ind + 0)r collaborators.txt" README.md
          
          rm collaborators.txt
          
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Инициализирован README.md"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}


    # Removing initialization files job   
  self-removing:
    needs: [repo-determinating, init-readme]
    if: ${{ needs.repo-determinating.outputs.repo-is-template == 'false' && needs.repo-determinating.outputs.commit-is-init == 'true' }}
    runs-on: ubuntu-latest
     
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2

      - name: Self-removing commit
        run: |
          git pull
          
          rm ".github/workflows/init-repo.yml"
          rm ".github/workflows/INIT_README.md"
          
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Удалён инициализирующий workflow"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}



  # Main branch protection rule changing job    
  branch-protection-rule-changing:
    needs: [repo-determinating, init-readme, self-removing]
    if: ${{ needs.repo-determinating.outputs.repo-is-template == 'false' && needs.repo-determinating.outputs.commit-is-init == 'true' }}
    runs-on: ubuntu-latest
     
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2

      - name: Adding "Teachers" team to repository
        run: |
          TEAM_SLUG="teachers"
          curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_SETTINGS_ADMIN_CLASSIC_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/${{ github.repository_owner }}/teams/${TEAM_SLUG}/repos/${{ github.repository }} \
            -d '{"permission":"admin"}'
      
      - name: Changing main branch protection rule
        run: |
          curl -X PUT \
            -H "Authorization: Bearer ${{ secrets.REPO_SETTINGS_ADMIN_CLASSIC_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/branches/main/protection \
              -d '{
                    "required_status_checks": {
                        "strict": true,
                        "contexts": []
                    },
                    "enforce_admins": false,
                    "required_pull_request_reviews": {
                        "dismissal_restrictions": {
                            "users": [],
                            "teams": [
                                "teachers"
                            ]
                        },
                        "dismiss_stale_reviews": false,
                        "require_code_owner_reviews": false,
                        "required_approving_review_count": 1,
                        "bypass_pull_request_allowances": {
                            "users": [],
                            "teams": [
                                "teachers"
                            ]
                        }
                    },
                    "restrictions": null,
                    "required_linear_history": false,
                    "allow_force_pushes": true,
                    "required_conversation_resolution": true
                  }' 
