name: Branch Protection Rule changing via GH API

on:
  workflow_call:
permissions: write-all

jobs:
   branch-protection-rule-changing:
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2
        
      - name: Adding "Teachers" team to repository
        run: |
          TEAM_SLUG="teachers"
          curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_SETTINGS_ADMIN_CLASSIC_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/${{ github.repository_owner }}/teams/${TEAM_SLUG}/repos/${{ github.repository }} \
            -d '{"permission":"admin"}'
      
      - name: Changing main branch protection rule
        run: |
          curl -X PUT \
            -H "Authorization: Bearer ${{ secrets.REPO_SETTINGS_ADMIN_CLASSIC_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/branches/main/protection \
              -d '{
                    "required_status_checks": {
                        "strict": true,
                        "contexts": []
                    },
                    "enforce_admins": false,
                    "required_pull_request_reviews": {
                        "dismissal_restrictions": {
                            "users": [],
                            "teams": [
                                "teachers"
                            ]
                        },
                        "dismiss_stale_reviews": false,
                        "require_code_owner_reviews": false,
                        "required_approving_review_count": 1,
                        "bypass_pull_request_allowances": {
                            "users": [],
                            "teams": [
                                "teachers"
                            ]
                        }
                    },
                    "restrictions": null,
                    "required_linear_history": false,
                    "allow_force_pushes": true,
                    "required_conversation_resolution": true
                  }' 

      - name: Self-removing
        run: |
          FILE_PATH=".github/workflows/BPR_setting.yml"
          SHA=$(git rev-parse HEAD:${FILE_PATH})
          
          curl -L \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_SETTINGS_ADMIN_CLASSIC_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/contents/${FILE_PATH} \
            -d "{
                    \"message\": \"BPR_setting.yml removed\",
                    \"committer\": {
                        \"name\": \"Monalisa Octocat\",
                        \"email\": \"octocat@github.com\"
                    },
                    \"sha\": \"${SHA}\"
                 }" 
                    },
                    \"sha\": \"${SHA}\"
                 }" 
