on:
  pull_request_review:
    types: [submitted]

jobs:
  telegram-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check review status
        id: check-review-status
        run: echo "REVIEW_STATUS=${{ github.event.review.state }}" >> $GITHUB_OUTPUT
      
      - name: Get repository name
        run: |
          echo "REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)" >> $GITHUB_ENV

      - name: Get branches names
        id: get-branches-names
        run: |
          echo "BASE_BRANCH_NAME=${{ github.event.pull_request.base.ref }}" >> $GITHUB_OUTPUT
          echo "HEAD_BRANCH_NAME=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
          echo "BASE_BRANCH_LINK=https://github.com/${{ github.repository }}/tree/${{ github.event.pull_request.base.ref }}" >> $GITHUB_OUTPUT
          echo "HEAD_BRANCH_LINK=https://github.com/${{ github.repository }}/tree/${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT

      - name: Get review body
        id: get-review-body
        run: |
          if [[ -n "${{ github.event.review.body }}" ]]; then
            REVIEW_BODY=""
            REVIEW_BODY+="\n"
            REVIEW_BODY+="💬 *Коммент:* ${{ github.event.review.body }}"
            REVIEW_BODY+="\n"

            echo "REVIEW_BODY<<EOF" >> $GITHUB_ENV
            echo -e $REVIEW_BODY >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          else
            echo "REVIEW_BODY=" >> $GITHUB_ENV
          fi

      - name: PR approved telegram notify
        if: steps.check-review-status.outputs.REVIEW_STATUS == 'approved'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_PROGRAMMINGBOT_TO }}
          token: ${{ secrets.TELEGRAM_PROGRAMMINGBOT_TOKEN }}
          format: markdown
          message: | #https://help.github.com/en/actions/reference/contexts-and-expression-syntax-for-github-actions#github-context
            @${{ github.event.pull_request.user.login }}, *твой Pull Request одобрен! Можешь слить ветки!* 🎉
            
            💻 *Проект:*  ${{ env.REPO_NAME }}

            🏷️ *Имя PR:* ${{ github.event.pull_request.title }}
            
            🌿 *Ветки:*  [${{ steps.get-branches-names.outputs.BASE_BRANCH_NAME }}](${{ steps.get-branches-names.outputs.BASE_BRANCH_LINK }}) <-- [${{ steps.get-branches-names.outputs.HEAD_BRANCH_NAME }}](${{ steps.get-branches-names.outputs.HEAD_BRANCH_LINK }})
            
            ✅ *Ревьюер:*  @${{ github.event.review.user.login }}
            ${{ env.REVIEW_BODY }}
            🔗 *Ссылка:*  [тыксюда](${{ github.event.pull_request.html_url }}) 

      - name: PR commented telegram notify
        if: steps.check-review-status.outputs.REVIEW_STATUS == 'commented'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_PROGRAMMINGBOT_TO }}
          token: ${{ secrets.TELEGRAM_PROGRAMMINGBOT_TOKEN }}
          format: markdown
          message: | #https://help.github.com/en/actions/reference/contexts-and-expression-syntax-for-github-actions#github-context
            @${{ github.event.pull_request.user.login }}, *твой Pull Request прокомментирован!* 📝
            
            💻 *Проект:*  ${{ env.REPO_NAME }}

            🏷️ *Имя PR:* ${{ github.event.pull_request.title }}
            
            🌿 *Ветки:*  [${{ steps.get-branches-names.outputs.BASE_BRANCH_NAME }}](${{ steps.get-branches-names.outputs.BASE_BRANCH_LINK }}) <-- [${{ steps.get-branches-names.outputs.HEAD_BRANCH_NAME }}](${{ steps.get-branches-names.outputs.HEAD_BRANCH_LINK }})
            
            ❎ *Ревьюер:*  @${{ github.event.review.user.login }}
            ${{ env.REVIEW_BODY }}
            🔗 *Ссылка:*  [тыксюда](${{ github.event.pull_request.html_url }}) 

      - name: PR changes requested telegram notify
        if: steps.check-review-status.outputs.REVIEW_STATUS == 'changes_requested'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_PROGRAMMINGBOT_TO }}
          token: ${{ secrets.TELEGRAM_PROGRAMMINGBOT_TOKEN }}
          format: markdown
          message: | #https://help.github.com/en/actions/reference/contexts-and-expression-syntax-for-github-actions#github-context
            @${{ github.event.pull_request.user.login }}, *в твоём Pull Request требуются изменения* ☝️
            
            💻 *Проект:*  ${{ env.REPO_NAME }}

            🏷️ *Имя PR:* ${{ github.event.pull_request.title }}
            
            🌿 *Ветки:*  [${{ steps.get-branches-names.outputs.BASE_BRANCH_NAME }}](${{ steps.get-branches-names.outputs.BASE_BRANCH_LINK }}) <-- [${{ steps.get-branches-names.outputs.HEAD_BRANCH_NAME }}](${{ steps.get-branches-names.outputs.HEAD_BRANCH_LINK }})
            
            ❎ *Ревьюер:*  @${{ github.event.review.user.login }}
            ${{ env.REVIEW_BODY }}
            🔗 *Ссылка:*  [тыксюда](${{ github.event.pull_request.html_url }}) 
